### ISSUE TITLE
Error when using my home build.

### ISSUE THREAD

**Issue by 68foxboris** [DimitarCC/iptv-m3u-reader#1]
I have Python 3.12,maybe that's why I get this error.

`16:33:01.0623 Traceback (most recent call last):
16:33:01.0624   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2331, in __onCreate
16:33:01.0630 [Directories] Line 73: Wrote '1' to file '/proc/stb/lcd/symbol_network'.
16:33:01.0637   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2437, in zap
16:33:01.0640   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 2363, in checkTimeshiftRunning
16:33:01.0643   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 11, in __call__
16:33:01.0646   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2451, in zapCheckTimeshiftCallback
16:33:01.0649   File "/home/foxbob/14.2/openpli-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-systemplugins-m3uiptv/1.0+git/image/usr/lib/enigma2/python/Plugins/SystemPlugins/M3UIPTV/plugin.py", line 334, in playServiceWithIPTV
16:33:01.0652   File "/home/foxbob/14.2/openpli-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-systemplugins-m3uiptv/1.0+git/image/usr/lib/enigma2/python/Plugins/SystemPlugins/M3UIPTV/IPTVProviders.py", line 4, in processService
16:33:01.0656 AttributeError: 'tuple' object has no attribute 'toString'
`

**Comment by Huevos** [comment]
Nothing to do with Py 3.12. That is what we are using.

**Comment by Huevos** [comment]
How do we reproduce the crash. Please give exact steps.

**Comment by Huevos** [comment]
From the crash log it appears you are not running an official version of PLi.

**Comment by 68foxboris** [comment]
This is my home build,I made a mistake when applying changes from git openpli.
![1_0_16_51F_D_70_1680000_0_0_0_20241011170640](https://github.com/user-attachments/assets/c308b6cf-ea4b-49ad-9245-ecd6cc2a8ef1)
