### ISSUE TITLE
M3UIPTV - can't install

### ISSUE THREAD

**Issue by Orlandoxx** [DimitarCC/iptv-m3u-reader#16]
![m3uiptv_error](https://github.com/user-attachments/assets/7a1dab93-a974-436a-a3d9-e073ad14436d)

**Comment by Huevos** [comment]
Yes, the index is out of sync on that plugin because I was doing some test builds of the translation stuff. I'll do a rebuild of vix shortly.

**Comment by Orlandoxx** [comment]
Now it is okay, thanx.
